finalapp/urls.py
from django.urls import path
from .views import *
# from .views import HomeView, ContactView

app_name="finalapp"

urlpatterns=[

	path("table/signup/", TableSignupView.as_view(), name = 'tablesignup'),
	path("table/login/", TableLoginView.as_view(), name = 'tablelogin'),
	path("signout/", SignoutView.as_view(), name = "signout"),


	path("home/", ClientHomeView.as_view(), name = 'clienthome'),

    path('menu/list/', ClientMenuListView.as_view(), name='clientmenulist'),

    path('', ClientItemListView.as_view(), name='clientitemlist'),

	path('menu/<int:pk>/detail/', ClientMenuDetailView.as_view(), name = 'clientmenudetail'),

	path("basket/", ClientBasketView.as_view(), name = 'clientbasket'),
    path("add-to-basket/<int:pk>/", AddToBasketView.as_view(), name = "addtobasket"),
    path("manage-basket/<int:pk>/<action>/", ManageBasketView.as_view(), name = "managebasket"),
    path("empty-basket/", EmptyBasketView.as_view(), name = 'emptybasket'),

    path("order/create/", OrderCreateView.as_view(), name = 'ordercreate'),
    path("order/list/", OrderListView.as_view(), name = 'orderlist'),
    path("order/<int:pk>/detail/", OrderDetailView.as_view(), name = 'orderdetail'),





    path("search/", ClientSearchView.as_view(), name = "clientsearch"),



	path("pi/", ClientPiHomeView.as_view(), name = 'clientpihome'),
    path("hardware/", HardwareView.as_view(), name = "clienthardware"),
    path("led/", LedView.as_view(), name = "clientled"),
    path("fan/", FanView.as_view(), name = "clientfan"),
    path("buzzer/", BuzzerView.as_view(), name = "clientbuzzer"),
    
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++



    path("emenu/admin/signin/", AdminSigninView.as_view(), name = "adminsignin"),
    path("emenu/admin/signout/", AdminSignoutView.as_view(), name = "adminsignout"),
    
    path("emenu/admin/", AdminHomeView.as_view(), name = 'adminhome'),

    # path("emenu/admin/service/list/", AdminServiceListView.as_view(), name = 'adminservicelist'),
    # path("emenu/admin/service/<int:pk>/detail/", AdminServiceDetailView.as_view(),
    #     name = 'adminservicedetail'),
    # path("emenu/admin/service/create/", AdminServiceCreateView.as_view(),
    #     name = 'adminservicecreate'),
    # path("emenu/admin/service/<int:pk>/update/", AdminServiceUpdateView.as_view(),
    #     name = 'adminserviceupdate'),
    # path("emenu/admin/service/<int:pk>/delete/", AdminServiceDeleteView.as_view(),
    #     name = 'adminservicedelete'),

    path("emenu/admin/menu/list/", AdminMenuListView.as_view(), name = 'adminmenulist'),
    path("emenu/admin/menu/<int:pk>/detail/", AdminMenuDetailView.as_view(),
        name = 'adminmenudetail'),
    path("emenu/admin/menu/create/", AdminMenuCreateView.as_view(),
        name = 'adminmenucreate'),
    path("emenu/admin/menu/<int:pk>/update/", AdminMenuUpdateView.as_view(),
        name = 'adminmenuupdate'),
    path("emenu/admin/menu/<int:pk>/delete/", AdminMenuDeleteView.as_view(),
        name = 'adminmenudelete'),

    path("emenu/admin/item/list/", AdminItemListView.as_view(), name = 'adminitemlist'),
    path("emenu/admin/item/<int:pk>/detail/", AdminItemDetailView.as_view(),
        name = 'adminitemdetail'),
    path("emenu/admin/item/create/", AdminItemCreateView.as_view(),
        name = 'adminitemcreate'),
    path("emenu/admin/item/<int:pk>/update/", AdminItemUpdateView.as_view(),
        name = 'adminitemupdate'),
    path("emenu/admin/item/<int:pk>/delete/", AdminItemDeleteView.as_view(),
        name = 'adminitemdelete'),


    # path("emenu/admin/specialitem/list/", AdminSpecialItemListView.as_view(),
    #     name = 'adminspecialitemlist'),
    # path("emenu/admin/specialitem/<int:pk>/detail/", AdminSpecialItemDetailView.as_view(),
    #     name = 'adminspecialitemdetail'),
    # path("emenu/admin/specialitem/create/", AdminSpecialItemCreateView.as_view(),
    #     name = 'adminspecialitemcreate'),
    # path("emenu/admin/specialitem/<int:pk>/update/", AdminSpecialItemUpdateView.as_view(),
    #     name = 'adminspecialitemupdate'),
    # path("emenu/admin/specialitem/<int:pk>/delete/", AdminSpecialItemDeleteView.as_view(),
    #     name = 'adminspecialitemdelete'),


    path("emenu/admin/staff/list/", AdminStaffListView.as_view(), name = 'adminstafflist'),
    # path("emenu/admin/staff/signup/", AdminStaffSignupView.as_view(),
    #     name = 'adminstaffsignup'),
    path("emenu/admin/staff/create/", AdminStaffCreateView.as_view(), name = 'adminstaffcreate'),
    path("emenu/admin/staff/<int:pk>/detail/", AdminStaffDetailView.as_view(), name = 'adminstaffdetail'),
    path("emenu/admin/staff/<int:pk>/delete/", AdminStaffDeleteView.as_view(), name = 'adminstaffdelete'),
    # path("emenu/admin/staff/signin/", AdminStaffSigninView.as_view(),
    #     name = 'adminstaffsignin'),


    path("emenu/admin/basket/list/", AdminBasketListView.as_view(), name = 'adminbasketlist'),
    path("emenu/admin/order/list/", AdminOrderListView.as_view(), name = 'adminorderlist'),
    path("emenu/admin/order/<int:pk>/update/", AdminOrderUpdateView.as_view(),
        name = 'adminorderupdate'),
    path("emenu/admin/order/<int:pk>/detail/", AdminOrderDetailView.as_view(),
        name = 'adminorderdetail'),

    path("emenu/admin/search/", AdminSearchView.as_view(), name = "adminsearch"),


    path("emenu/kitchen/home/", KitchenHomeView.as_view(), name = "kitchenhome"),
    path("emenu/kitchen/order/list/", KitchenOrderListView.as_view(), name = "kitchenorderlist"),
    path("emenu/kitchen/order/<int:pk>/detail/", KitchenOrderDetailView.as_view(),
        name = "kitchenorderdetail"),

     path("emenu/try/", TryView.as_view(), name = "try"),


]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finalapp.urls')),

    path("", include('finaleapp.urls')),
   
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/clienttemplates/buzzer.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %} Buzzer {% endblock %}

{% block content %}


<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'finalapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page"><a href="{% url 'finalapp:clienthardware' %}">Hardware</a></li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">Buzzer </li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

              <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">
                       <form method="POST">
                        {% csrf_token %}
                        <select name = "buzzer_switch">
                          <option value="buzzeron">Buzzer OFF</option>
                          <option value="buzzeroff">Buzzer ON</option>
                         
                        </select>
                        <button>Submit</button>
                      </form>
                    </h3>
                    <span class="w3-line"></span>
                </div>
                 
         
  

{% endblock %}
  
  

templates/clienttemplates/clientaddtobasket.html
<h3>Item Successfully Added To Your Basket</h3>

templates/clienttemplates/clientbasket.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Your Basket
{% endblock %}


{% block basket %}active{% endblock %}
{% block content %}





<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href=" {% url 'finalapp:clienthome' %} ">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">Basket</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->
        <!-- items -->
       
        <section class="wthree-row services-bg" id="serv-bot">

                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    {% if request.user.is_authenticated %}
                    <h3 class="agile-title text-uppercase">Basket of {{request.user}}</h3>
                    {% else %}
                    <h3 class="agile-title text-uppercase">Your Basket</h3>
                    {% endif %}
                    <span class="w3-line"></span>
                </div>
                
                <button type="btn" href=" {% url 'finalapp:emptybasket' %} " id="empty-basket" class="ml-lg-3">Empty Basket</button>

                <p id="myp" class="ml-lg-3"></p>
                    <div class="row">
                        <div class="col-md" id="my-content">
                            <table class="table" id="my-table">
                                <thead>
                                    <tr>
                                        <th style="text-align: center;">Ordered Items</th>
                                        <th>Rate</th>
                                        <th>Quantity</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for basketitem in mainbasket.basketitem_set.all %}
                                    <tr>
                                        <td  style="text-align: center;">
                                            {{basketitem.item.name}}  
                                            <img src="{{basketitem.item.photo.url}}" alt="item" width="75">
                                        </td>
                                        <td>{{basketitem.rate}}</td>
                                        <td>
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'dcr' %}" class="manage-basket">-</button>      {{basketitem.quantity}}      
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'inr' %}" class="manage-basket">+</button>
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'rmv' %}" class="manage-basket">x</button>
                                        </td>
                                        <td>{{basketitem.subtotal}}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="5" class="text-center">No Item exists in your basket <a href="{% url 'finalapp:clientitemlist' %}">Add to Basket Now</a></td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <th></th>
                                        <th colspan="2" class="text-right">Total: </th>
                                        <th>{{mainbasket.total}}</th>
                                    </tr>
                                     <tr>
                                        {% if mainbasket.total.is_None %}
                                        <th></th>
                                        {% else %}
                                        <th></th>
                                        <th colspan="2" class="text-right"><button type="button" data-toggle="modal" data-target="#exampleModal22">Order Now</button></th>
                                        {% endif %}
                                    </tr>
                                </tbody>
                                
                            </table>
                        </div>

                        <!-- <div class="col-md-4"> -->
                            
                            <!-- <button type="button" data-toggle="modal" data-target="#exampleModal22">Order Now</button> -->
                        <!-- </div> -->
                    </div>
       </section>



       <div class="modal fade" id="exampleModal22" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Order Once Placed Can't Be Modified Again</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body" id="" >
                        <!-- <img src=" {% static 'clientstatic/images/modal.jpg' %} " alt="" class="img-fluid" /> -->
                        <!-- <h4 style="color: green;">Total Order Price: Rs.{{mainbasket.total}}</h4> -->
                        <form action="{% url 'finalapp:ordercreate' %}" method="post" class="p-3">
                            {% csrf_token %}
                            {{orderform.as_p}}
                            <div class="right-w3l">
                                <input type="submit" class="form-control" value="Order">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>


{% endblock %}

{% block js %}


<!-- Script to increase decrease and remove basket-items -->
<script type="text/javascript">
    $(document).ready(function(){
        $(".manage-basket").on("click", function(){
            // alert("CLicked button")
            $("#my-content").on("click", ".manage-basket", function(){
            var url_end_point = $(this).attr("href");
            // alert(url_end_point)
            $.ajax({
                method: 'get',
                url: url_end_point,
                data: {

                },
                success: function(data){
                    $("#my-content").load("#my-content #my-table");
                    $('#myp').html(data).css("display", 'block');
                    $("#myp" ).click(function() {
                      $("#myp" ).fadeOut( "slow" );
                        });
            }
            })
        })
        })
    })
</script>

<!-- Script to Empty Basket -->
<script type="text/javascript">
    $(document).ready(function(){
        $("#empty-basket").on("click", function(){
            var empty_url = $(this).attr("href");
            $.ajax({
                method: 'get',
                url: empty_url,
                data: {

                },
                success: function(data){
                    $("#my-content").load("#my-content #my-table");
                    $('#myp').html(data).css("display", 'block');
                    $("#myp" ).click(function() {
                        $("#myp" ).fadeOut( "slow" );
                            }); 
                }
            });
        });
    });
</script>

{% endblock %}

templates/clienttemplates/clienthardware.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %} Hardware {% endblock %}

{% block content %}


<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'finalapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">Hardware form</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

         
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">Hardware form</h3>
                    <span class="w3-line"></span>
                </div>
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase"> <a href="{% url 'finalapp:clientled' %}">Led Interface 	<i class="fas fa-lightbulb"></i></a></h3>
                    <span class="w3-line"></span>
                </div>
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase"><a href="{% url 'finalapp:clientfan' %}">FAN Interface <i class="fas fa-asterisk"></i></a></h3>
                    <span class="w3-line"></span>
                </div>
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase"><a href="{% url 'finalapp:clientbuzzer' %}">BUZZER Interface <i class="fas fa-volume-up"></i></a></h3>
                    <span class="w3-line"></span>
                </div>




  
  
 
    
  
    

{% endblock %}
  
  

templates/clienttemplates/clientled.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %} Hardware {% endblock %}

{% block content %}


<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'finalapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page"><a href="{% url 'finalapp:clienthardware' %}">Hardware</a></li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">LED </li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

              <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">
                       <form method="POST">
                        {% csrf_token %}
                        <select name = "led_switch">
                          <option value="ledon">LED OFF</option>
                          <option value="ledoff">LED ON</option>
                         
                        </select>
                        <button>Submit</button>
                      </form>
                    </h3>
                    <span class="w3-line"></span>
                </div>
                 
         
  

{% endblock %}
  
  

templates/clienttemplates/clientmanagebasket.html
<h4>
	{{message}}
</h4>

templates/clienttemplates/clientmenudetail.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}


{% block title %}
Client Menu Detail Page
{% endblock %}

{% block menudetail %}active{% endblock %}

{% block content %}



    <!-- main content start-->
    <div id="page-wrapper">
    <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href=" {% url 'finalapp:clienthome' %} ">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">
                            <a href=" {% url 'finalapp:clientmenulist' %} ">Menu</a></li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">{{menuobject.title}}'s Detail</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->
        <!-- items -->
       
        <div class="py-lg-5 py-3 bg-pricemain text-center">
            <h3 class="agile-title text-uppercase">Under the Menu of  '{{menuobject.title}}'</h3>
            <span class="w3-line"></span>
        </div>
          
        <div class="row">
            <!-- For Displaying Root Items Only -->
            {% for item in menuobject.item_set.all %}
            <div class="col-md-3">
                <img class="card-img-top" src="{{ item.photo.url }}" style=' width: 250; height: mx-auto;'>
                <div class="card-body bg-light text-center">
                    <h3><a href="">{{item.name}}</a></h3>
                    <h4>Price: Rs. {{item.price}}</h4>
                    <button data-href=" {% url 'finalapp:addtobasket' item.id %} " class="add-to-basket" type="btn btn-success" style="text-decoration: none; text-transform: uppercase; color: green;">Order Now</button>
                </div>
            </div>
            {% endfor %}
            <!-- End of Displaying Root Items Only -->
        </div>        

           




{% endblock %}

templates/clienttemplates/clientmenulist.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Client Menu List page
{% endblock %}

{% block content %}
<!-- main content start-->
    <div id="page-wrapper">
        <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href="{% url 'finalapp:clienthome' %}">Home</a>
                        </li>
                        <li class="breadcrumb-item">
                            <a href=" {% url 'finalapp:clientmenulist' %} ">Menu-List</a>
                        </li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->

  		<section class="wthree-row pt-md-5 pt-0">
            <div class="py-sm-5 pt-3 pb-4 bg-pricemain text-center">
                <h3 class="agile-title text-uppercase">All Menus</h3>
                <span class="w3-line"></span>
            </div>
             <div class="row">
                {% for menus in allmenus %}
                    <div class="col-md-3">
                        <img class="card-img-top" src=" {% static 'clientstatic/images/g9.jpg' %} " width="250" height="200">
                        <div class="card-body bg-light text-center">
                            <h5 class="card-title "><a href=" {% url 'finalapp:clientmenudetail' menus.id %} ">{{ menus.title }}</a></h5>
                        </div>
                    </div>
                {% endfor %}
            </div>
                    
        </section>


{% endblock %}

templates/clienttemplates/clientordercreate.html
{% extends 'clienttemplates/clientbase.html' %}
{% load static %}

{% block title %}
Ordering Page
{% endblock %}

{% block content %}



<!-- main content start-->
    <div id="page-wrapper">
         <!-- inner banner -->
        <div class="inner-banner">
        </div>
        <!-- //inner banner -->
        <!-- breadcrumbs -->
        <div class="inner-bc">
            <div class="container">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item">
                            <a href=" {% url 'finalapp:clienthome' %} ">Home</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">
                        	<a href=" {% url 'finalapp:clientbasket' %} ">Basket</a>
                        </li>
                        <li class="breadcrumb-item active  text-capitalize" aria-current="page">Order</li>
                    </ol>
                </nav>
            </div>
        </div>
        <!-- //breadcrumbs -->
        <!-- items -->
       
        <section class="wthree-row services-bg" id="serv-bot">
                <div class="py-lg-5 py-3 bg-pricemain text-center">
                    <h3 class="agile-title text-uppercase">Manage Your Order</h3>
                    <span class="w3-line"></span>
                </div>

                <div class="row">

                	<div class="col-md-8" >
		                <div class="py-lg-5 py-3 bg-pricemain text-center">
		                    {% if request.user.is_authenticated %}
		                    <h3>Basket of {{request.user}}</h3>
		                    {% else %}
		                    <h3>Your Basket</h3>
		                    {% endif %}
		                    <span class="w3-line"></span>
		                </div>
		                <button type="btn" href=" {% url 'finalapp:emptybasket' %} " id="empty-basket" class="ml-lg-3">Empty Basket</button>
		                <p id="myp" class="ml-lg-3"></p>
                        <div id="my-content">
                            <table class="table" id="my-table">
                                <thead>
                                    <tr>
                                        <th style="text-align: center;">Ordered Items</th>
                                        <th>Rate</th>
                                        <th>Quantity</th>
                                        <th>Subtotal</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for basketitem in basket_obj.basketitem_set.all %}
                                    <tr>
                                        <td  style="text-align: center;">
                                            {{basketitem.item.name}}  
                                            <img src="{{basketitem.item.photo.url}}" alt="item" width="75">
                                        </td>
                                        <td>{{basketitem.rate}}</td>
                                        <td>
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'dcr' %}" class="manage-basket">-</button>      {{basketitem.quantity}}      
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'inr' %}" class="manage-basket">+</button>
                                            <button type="btn" href="{% url 'finalapp:managebasket' basketitem.id 'rmv' %}" class="manage-basket">x</button>
                                        </td>
                                        <td>{{basketitem.subtotal}}</td>
                                    </tr>
                                    {% empty %}
                                    <tr>
                                        <td colspan="5" class="text-center">No Item exists in your basket <a href="{% url 'finalapp:clientitem' %}">Add to Basket Now</a></td>
                                    </tr>
                                    {% endfor %}
                                    <tr>
                                        <th></th>
                                        <th colspan="2" class="text-right">Total: </th>
                                        <th>{{basket_obj.total}}</th>
                                    </tr>
                                </tbody>
                                
                            </table>
                        </div>
                    </div>

                    <div class="col-md-4">
						<div class="py-lg-5 py-3 bg-pricemain text-center">
							<h3 class="agile-title text-uppercase">Create Order Now</h3>
							<span class="w3-line"></span>
						</div>
						<form method="post">
							{% csrf_token %}							
							{{form.as_p}}
							<input type="submit" name="Order">
						</form>
                    </div>

                </div>
       </section>



{% endblock %}

{% block js %}


<!-- Script to increase decrease and remove basket-items -->
<script type="text/javascript">
    $(document).ready(function(){
        $(".manage-basket").on("click", function(){
            // alert("CLicked button")
            $("#my-content").on("click", ".manage-basket", function(){
            var url_end_point = $(this).attr("href");
            // alert(url_end_point)
            $.ajax({
                method: 'get',
                url: url_end_point,
                data: {

                },
                success: function(data){
                    $("#my-content").load("#my-content #my-table");
                    $('#myp').html(data).css("display", 'block');
                    $("#myp" ).click(function() {
                      $("#myp" ).fadeOut( "slow" );
                        });
            }
            })
        })
        })
    })
</script>

<!-- Script to Empty Basket -->
<script type="text/javascript">
    $(document).ready(function(){
        $("#empty-basket").on("click", function(){
            var empty_url = $(this).attr("href");
            $.ajax({
                method: 'get',
                url: empty_url,
                data: {

                },
                success: function(data){
                    $("#my-content").load("#my-content #my-table");
                    $('#myp').html(data).css("display", 'block');
                    $("#myp" ).click(function() {
                        $("#myp" ).fadeOut( "slow" );
                            }); 
                }
            });
        });
    });
</script>

{% endblock %}

templates/clienttemplates/tablelogin.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>
	E-Menu-Table Login Page		
	</title>
	<!-- <link href=" {% static 'clientstatic/css/bootstrap.css' %} " rel='stylesheet' type='text/css' /> -->
</head>
<body class="container-fluid">

<div class="row">
	<div class="col-md-6 mx-auto">
		<h4>Table User Signin Form</h4><hr>
		<form method="post">
			{% if error %}
			<li class="text-danger">{{error}}</li>
			{% endif %}
			{% csrf_token %}
			{{form.as_p}}
			<input type="submit" name="Login" class="btn btn-info">		
		</form>	
	</div>
</div>

<div class="row">
	<br>
	Or, Create New Table User??
	<a href=" {% url 'finalapp:tablesignup' %} "><button>Click Here</button></a>
	
</div>





</body>
</html>