finalapp/urls.py
from django.urls import path
from .views import *
# from .views import HomeView, ContactView

app_name="finalapp"

urlpatterns=[

	path("table/signup/", TableSignupView.as_view(), name = 'tablesignup'),
	path("table/login/", TableLoginView.as_view(), name = 'tablelogin'),
	path("signout/", SignoutView.as_view(), name = "signout"),


	path("home/", ClientHomeView.as_view(), name = 'clienthome'),

    path('menu/list/', ClientMenuListView.as_view(), name='clientmenulist'),

    path('', ClientItemListView.as_view(), name='clientitemlist'),

	path('menu/<int:pk>/detail/', ClientMenuDetailView.as_view(), name = 'clientmenudetail'),

	path("basket/", ClientBasketView.as_view(), name = 'clientbasket'),
    path("add-to-basket/<int:pk>/", AddToBasketView.as_view(), name = "addtobasket"),
    path("manage-basket/<int:pk>/<action>/", ManageBasketView.as_view(), name = "managebasket"),
    path("empty-basket/", EmptyBasketView.as_view(), name = 'emptybasket'),

    path("order/create/", OrderCreateView.as_view(), name = 'ordercreate'),
    path("order/list/", OrderListView.as_view(), name = 'orderlist'),
    path("order/<int:pk>/detail/", OrderDetailView.as_view(), name = 'orderdetail'),





    path("search/", ClientSearchView.as_view(), name = "clientsearch"),



	path("pi/", ClientPiHomeView.as_view(), name = 'clientpihome'),
    path("hardware/", HardwareView.as_view(), name = "clienthardware"),
    path("led/", LedView.as_view(), name = "clientled"),
    path("fan/", FanView.as_view(), name = "clientfan"),
    path("buzzer/", BuzzerView.as_view(), name = "clientbuzzer"),
    
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++
#+++++++++++++++++++++++++++++



    path("emenu/admin/signin/", AdminSigninView.as_view(), name = "adminsignin"),
    path("emenu/admin/signout/", AdminSignoutView.as_view(), name = "adminsignout"),
    
    path("emenu/admin/", AdminHomeView.as_view(), name = 'adminhome'),

    # path("emenu/admin/service/list/", AdminServiceListView.as_view(), name = 'adminservicelist'),
    # path("emenu/admin/service/<int:pk>/detail/", AdminServiceDetailView.as_view(),
    #     name = 'adminservicedetail'),
    # path("emenu/admin/service/create/", AdminServiceCreateView.as_view(),
    #     name = 'adminservicecreate'),
    # path("emenu/admin/service/<int:pk>/update/", AdminServiceUpdateView.as_view(),
    #     name = 'adminserviceupdate'),
    # path("emenu/admin/service/<int:pk>/delete/", AdminServiceDeleteView.as_view(),
    #     name = 'adminservicedelete'),

    path("emenu/admin/menu/list/", AdminMenuListView.as_view(), name = 'adminmenulist'),
    path("emenu/admin/menu/<int:pk>/detail/", AdminMenuDetailView.as_view(),
        name = 'adminmenudetail'),
    path("emenu/admin/menu/create/", AdminMenuCreateView.as_view(),
        name = 'adminmenucreate'),
    path("emenu/admin/menu/<int:pk>/update/", AdminMenuUpdateView.as_view(),
        name = 'adminmenuupdate'),
    path("emenu/admin/menu/<int:pk>/delete/", AdminMenuDeleteView.as_view(),
        name = 'adminmenudelete'),

    path("emenu/admin/item/list/", AdminItemListView.as_view(), name = 'adminitemlist'),
    path("emenu/admin/item/<int:pk>/detail/", AdminItemDetailView.as_view(),
        name = 'adminitemdetail'),
    path("emenu/admin/item/create/", AdminItemCreateView.as_view(),
        name = 'adminitemcreate'),
    path("emenu/admin/item/<int:pk>/update/", AdminItemUpdateView.as_view(),
        name = 'adminitemupdate'),
    path("emenu/admin/item/<int:pk>/delete/", AdminItemDeleteView.as_view(),
        name = 'adminitemdelete'),


    # path("emenu/admin/specialitem/list/", AdminSpecialItemListView.as_view(),
    #     name = 'adminspecialitemlist'),
    # path("emenu/admin/specialitem/<int:pk>/detail/", AdminSpecialItemDetailView.as_view(),
    #     name = 'adminspecialitemdetail'),
    # path("emenu/admin/specialitem/create/", AdminSpecialItemCreateView.as_view(),
    #     name = 'adminspecialitemcreate'),
    # path("emenu/admin/specialitem/<int:pk>/update/", AdminSpecialItemUpdateView.as_view(),
    #     name = 'adminspecialitemupdate'),
    # path("emenu/admin/specialitem/<int:pk>/delete/", AdminSpecialItemDeleteView.as_view(),
    #     name = 'adminspecialitemdelete'),


    path("emenu/admin/staff/list/", AdminStaffListView.as_view(), name = 'adminstafflist'),
    # path("emenu/admin/staff/signup/", AdminStaffSignupView.as_view(),
    #     name = 'adminstaffsignup'),
    path("emenu/admin/staff/create/", AdminStaffCreateView.as_view(), name = 'adminstaffcreate'),
    path("emenu/admin/staff/<int:pk>/detail/", AdminStaffDetailView.as_view(), name = 'adminstaffdetail'),
    path("emenu/admin/staff/<int:pk>/delete/", AdminStaffDeleteView.as_view(), name = 'adminstaffdelete'),
    # path("emenu/admin/staff/signin/", AdminStaffSigninView.as_view(),
    #     name = 'adminstaffsignin'),


    path("emenu/admin/basket/list/", AdminBasketListView.as_view(), name = 'adminbasketlist'),
    path("emenu/admin/order/list/", AdminOrderListView.as_view(), name = 'adminorderlist'),
    path("emenu/admin/order/<int:pk>/update/", AdminOrderUpdateView.as_view(),
        name = 'adminorderupdate'),
    path("emenu/admin/order/<int:pk>/detail/", AdminOrderDetailView.as_view(),
        name = 'adminorderdetail'),

    path("emenu/admin/search/", AdminSearchView.as_view(), name = "adminsearch"),


    path("emenu/kitchen/home/", KitchenHomeView.as_view(), name = "kitchenhome"),
    path("emenu/kitchen/order/list/", KitchenOrderListView.as_view(), name = "kitchenorderlist"),
    path("emenu/kitchen/order/<int:pk>/detail/", KitchenOrderDetailView.as_view(),
        name = "kitchenorderdetail"),

     path("emenu/try/", TryView.as_view(), name = "try"),


]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('finalapp.urls')),

    path("", include('finaleapp.urls')),
   
    

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/admintemplates/adminmenucreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Menu Create Page
{% endblock  %}

{% block content %}



	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Create New Menu</h2>
	<!--// main-heading -->

	 <!-- Forms-1 -->
    <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
        <form action="#" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    {{form.title}}
                </div>
            </div>
             <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Root</label>
                <div class="col-sm-10">
                    {{form.root}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-danger"><a href="{% url 'finalapp:adminmenulist' %}">Cancel</a></button>
                </div>
            </div>

        </form>
    </div>
    <!--// Forms-1 -->


{% endblock %}

templates/admintemplates/adminmenuupdate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Menu Update Page
{% endblock %}

{% block content %}

	
	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Update Menu</h2>
	<!--// main-heading -->

	 <!-- Forms-1 -->
    <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
        <form action="#" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    {{form.title}}
                </div>
            </div>
             <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Root</label>
                <div class="col-sm-10">
                    {{form.root}}
                </div>
            </div>
             <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
             <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-danger"><a href="{% url 'finalapp:adminmenulist' %}">Cancel</a></button>
                </div>
            </div>
        </form>
    </div>
    <!--// Forms-1 -->


{% endblock  %}

templates/admintemplates/adminorderdetail.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Order Detail Page
{% endblock %}

{% block content %}

	

	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Detail of Order ID : "{{orderobject.id}}"</h2>
	<h2 class="main-title-w3layouts mb-2 text-center">Order By : "{{orderobject.table.name}}"</h2>
	<!--// main-heading -->
	
	<div class="col-lg-12 px-sm-5 px-3">
            <h4><span>Your Basket Order Detail</span></h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>SN</th>
                        
                        <th>Ordered Item</th>
                        <th>Image</th>
                        <th>Subtotal(Rs.)</th>
                    </tr>
                </thead>
                <tbody>
                    {% for basketitem in orderobject.basket.basketitem_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                       
                        <td>{{basketitem.item}}</td>
                        <td><img src="{{basketitem.item.photo.url}}" width="80"></td>
                        <td>{{basketitem.rate}}*{{basketitem.quantity}} = {{basketitem.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    
                    <tr>
                        <th colspan="3" class="text-right">Total: </th>
                        <th>Rs.{{orderobject.total}}</th>
                    </tr>
                    <tr>
                        <th colspan="3" class="text-right">Payment Method:</th>
                        <th style="text-transform: uppercase;">{{orderobject.payment_method}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
	
	

   



{% endblock %}

templates/admintemplates/adminorderlist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Order LIst Page
{% endblock %}

{% block order %}active{% endblock %}

{% block content %}


	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Manage Orders</h2>
	<!--// main-heading -->

	<!-- table2 -->
        <div class="outer-w3-agile mt-3">
            <h4 class="tittle-w3-agileits mb-4">List Of All Orders</h4>
            <a class="text-info" href="{% url 'finalapp:adminorderlist' %}">All orders</a>
            <a class="text-info" href="{% url 'finalapp:adminorderlist' %}?status=neworder">New orders</a>
            <a class="text-info" href="{% url 'finalapp:adminorderlist' %}?status=preparedorder">Prepared Orders</a>
            <a class="text-info" href="{% url 'finalapp:adminorderlist' %}?status=deliveredorder">Delivered Orders</a>
            <div>

            	<!-- Top Pagination Start -->
                {% if allorders.has_other_pages %}
                <ul class="pagination">
                    {% if allorders.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ allorders.previous_page_number }}">Previous</a></li>
                    {% else %}
                    <li class="page-item disabled"><a class="page-link" href="#">Previous</a></li>
                    {% endif %}
                    {% for n in allorders.paginator.page_range %}
                        {% if allorders.number == n %}
                            <li class="page-item active"><span class="page-link">{{ n }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li class="page-item"><a class="page-link" href="?page={{ n }}">{{n}}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if allorders.has_next %}
                      <li class="page-item"><a class="page-link" href="?page={{ allorders.next_page_number}}">Next</a></li>
                    {% else %}
                      <li class="page-item disabled"><span class="page-link">Next</span></li>
                    {% endif %}
                </ul>
                {% endif %}
                <!-- Top Pagination Ends -->

            </div>
            <div style="text-align: right;" class="mr-2">
	        </div>
             <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Order ID</th>
                        <th scope="col">Basket ID</th>
                        <th scope="col">Table</th>
                        <th scope="col">Total</th>
                        <th scope="col">Order Status</th>
                        <th scope="col">Order Time</th>
                        <th scope="col">Pay Method</th>
                        <th scope="col">Manage</th>
                    </tr>
                </thead>
                <tbody>
                	{% for order in allorders %}
                	<!-- <tr> -->
                    <tr class='clickable-row' data-href=" {% url 'finalapp:adminorderdetail' order.id %} ">
                        <td>{{order.id}}</td>
                        <td>{{order.basket.id}}</td>
                        <td>{{order.table}}</td>
                        <td>{{order.total}}</td>
                        <td><button class="btn">{{order.order_status}}</button></td>
                        <td>{{order.created_at}}</td>
                        <td>{{order.payment_method}}</td>
                        <td>
                            <a href=" {% url 'finalapp:adminorderupdate' order.id %} "><button class="btn btn-success"><i class="fas fa-edit"></i></button></a>
                        	<!-- <button class="btn btn-danger"><i class="fas fa-trash-alt"></i></button></a> -->
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <!--// table2 -->




         <!-- Button trigger modal -->
          <!--   <div class="d-flex justify-content-around mb-5">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                   <i class="fas fa-trash-alt"></i>
                </button>
            </div> -->
            <!-- popup content -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <img src="images/ban4.jpg" class="img-fluid" alt="Responsive image">
                            <p class="paragraph-agileits-w3layouts mt-3">Maecenas interdum, metus vitae tincidunt porttitor, magna quam egestas sem, ac scelerisque
                                nisl nibh vel lacus. Proin eget gravida odio. Donec ullamcorper est eu accumsan cursus.</p>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="button" class="btn btn-primary">Save changes</button>
                        </div>
                    </div>
                </div>
            </div>
            <!--// popup content -->


{% endblock %}


{% block js %}

<script type="text/javascript">
	jQuery(document).ready(function($) {
		$(".clickable-row").click(function() {
			window.location = $(this).attr("data-href");
		});
	});
</script>


{% endblock %}

templates/admintemplates/adminservicecreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Service Create Page
{% endblock %}

{% block content %}

	
	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Create New Service</h2>
	<!--// main-heading -->

	 <!-- Forms-1 -->
    <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
        <form action="#" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Title</label>
                <div class="col-sm-10">
                    {{form.title}}
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-10">
                   {{form.image}}
                </div>
            </div>
             <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Content</label>
                <div class="col-sm-10">
                    {{form.content}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-danger"><a href="{% url 'finalapp:adminservicelist' %}">Cancel</a></button>
                </div>
            </div>

        </form>
    </div>
    <!--// Forms-1 -->


{% endblock  %}

templates/admintemplates/adminservicedelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Service Delete Page
{% endblock %}

{% block content %}

	
	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Service Delete</h2>
	<!--// main-heading -->
	<form method="POST">
		{% csrf_token %}
		Service ID = {{service.id}}<br>
		Are you Sure to delete service titled "{{service.title}}"?<br>
		<button class="btn btn-primary">yes</button>		
		<a href="/emenu/admin/service/list/" class="btn btn-info">cancel</a>
	</form>



{% endblock %}

templates/admintemplates/adminsignin.html
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->

{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <title>Modernize an Admin Panel Category Bootstrap Responsive Web Template | Login :: w3layouts</title>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Modernize Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //Meta Tags -->

    <!-- Style-sheets -->
    <!-- Bootstrap Css -->
    <link href=" {% static 'adminstatic/css/bootstrap.css' %} " rel="stylesheet" type="text/.css' %} " media="all" />
    <!-- Bootstrap Css -->
    <!-- Common Css -->
    <link href=" {% static 'adminstatic/css/style.css' %} " rel="stylesheet" type="text/.css' %} " media="all" />
    <!--// Common Css -->
    <!-- Fontawesome Css -->
    <link href=" {% static 'adminstatic/css/fontawesome-all.css' %} " rel="stylesheet">
    <!--// Fontawesome Css -->
    <!--// Style-sheets -->

    <!--web-fonts-->
    <link href="//fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!--//web-fonts-->
</head>

<body>
    <div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>
            <!--// main-heading -->
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                <form method="post">
                    {% csrf_token %}
                    {% if error %}
                    <li class="text-danger">{{error}}</li>
                    {% endif %}
                    {{form.as_p}}
                    <input type="submit" name="submit">

                    <!-- <div class="form-group">
                        <label>Email address</label>
                        <input type="email" class="form-control" placeholder="Enter email" required="">
                    </div>
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" class="form-control" placeholder="Password" required="">
                    </div>
                    <div class="d-sm-flex justify-content-between">
                        <div class="form-check col-md-6 text-sm-left text-center">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Remember me</label>
                        </div>
                        <div class="forgot col-md-6 text-sm-right text-center">
                            <a href="forgot.html">forgot password?</a>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary error-w3l-btn mt-sm-5 mt-3 px-4">Login</button>
                     -->
                </form>
                <p class="paragraph-agileits-w3layouts mt-4">Don't have an account
                    <a href="register.html">Create an account</a>
                </p>
                <h1 class="paragraph-agileits-w3layouts mt-2">
                    <a href=" {% url 'finalapp:adminhome' %} ">Back to Home</a>
                </h1>
            </div>

            <!-- Copyright -->
            <div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">
                <p>© 2018 Modernize . All Rights Reserved | Design by
                    <a href="http://w3layouts.com/"> W3layouts </a>
                </p>
            </div>
            <!--// Copyright -->
        </div>
    </div>


    <!-- Required common Js -->
    <script src=" {% static 'adminstatic/js/jquery-2.2.3.min.js' %} "></script>
    <!-- //Required common Js -->

    <!-- Js for bootstrap working-->
    <script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>
    <!-- //Js for bootstrap working -->

</body>

</html>

templates/admintemplates/adminstaffcreate.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Staff Create Page
{% endblock %}

{% block content %}

	
	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Create New Staff</h2>
	<!--// main-heading -->

	 <!-- Forms-1 -->
    <div class="outer-w3-agile col-xl mt-3 mr-xl-3">
        <form action="#" method="post" enctype="multipart/form-data">
        	{% csrf_token %}
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Name: </label>
                <div class="col-sm-10">
                    {{form.name}}
                </div>
            </div>
            <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Address: </label>
                <div class="col-sm-10">
                    {{form.address}}
                </div>
            </div>
             <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Mobile No.:</label>
                <div class="col-sm-10">
                    {{form.mobile}}
                </div>
            </div>
             <div class="form-group row">
                <label for="inputEmail3" class="col-sm-2 col-form-label">Position:</label>
                <div class="col-sm-10">
                    {{form.position}}
                </div>
            </div>
            <div class="form-group row">
                <label for="inputPassword3" class="col-sm-2 col-form-label">Image</label>
                <div class="col-sm-10">
                   {{form.photo}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-10">
                    <button type="submit" class="btn btn-danger"><a href="{% url 'finalapp:adminitemlist' %}">Cancel</a></button>
                </div>
            </div>

        </form>
    </div>
    <!--// Forms-1 -->


{% endblock  %}

templates/admintemplates/adminstaffdelete.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Staff Delete Page
{% endblock %}

{% block content %}

	
	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Staff Delete</h2>
	<!--// main-heading -->
	<form method="POST">
		{% csrf_token %}
		Staff ID = {{staff.id}}<br>
		Are you Sure to delete staff named "{{staff.name}}"?<br>
		<button class="btn btn-primary">yes</button>		
		<a href="/emenu/admin/staff/list/" class="btn btn-info">cancel</a>
	</form>



{% endblock %}

templates/admintemplates/adminstafflist.html
{% extends 'admintemplates/adminbase.html' %}
{% load static %}

{% block title %}
Admin Staff List
{% endblock %}


{% block css %}

<!-- widgets Css -->
<link href=" {% static 'adminstatic/css/widgets.css' %} " rel="stylesheet">
<!-- widgets Css -->

{% endblock %}

{% block staff %}active{% endblock %}

{% block content %}

	<!-- main-heading -->
	<h2 class="main-title-w3layouts mb-2 text-center">Manage Staffs</h2>
	<!--// main-heading -->

    <div style="text-align: right;" class="mr-2">
        <a href=" {% url 'finalapp:adminstaffcreate' %} " style="color: white;"><button class="btn btn-success"><i class="fas fa-plus"></i></button></a>
    </div>


	<!--// three-grids -->
    <div class="container-fluid">
        <div class="row">
        	{% for staff in allstaffs %}
            <!-- Profile -->
            <div class="outer-w3-agile col-xl-4 mt-3">
                <div class="profile-main-w3ls">
                    <div class="profile-pic wthree">
                        <img src="{{staff.photo.url}}" class="img-fluid" alt="Responsive image">
                        <h3>{{staff.name}}</h3>
                        <p>{{staff.position}}</p>
                    </div>
                    <div class="w3-message">
                        <a href=" {% url 'finalapp:adminstaffdetail' staff.id %} "><h5>About Me</h5></a>
                        <p>Mobile: {{staff.mobile}}</p>
                        <div class="w3ls-touch">

                            <div class="social">
                                <ul>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-facebook-f"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-twitter"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-linkedin-in"></i>
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#">
                                            <i class="fab fa-google-plus-g"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
                {% endfor %}
            <!--// Profiile -->
        </div>
    </div>


{% endblock %}


{% block js %}

    <script src=" {% static 'adminstatic/js/bootstrap.min.js' %} "></script>

{% endblock %}